name: Java CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, 'skip ci') && !contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        java: [ 17 ]

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v3
      with:
        java-version: "${{ matrix.java }}"
        distribution: 'temurin'

    - uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          .gradle/caches
        key: ${{ runner.os }}-gradle-JDK${{ matrix.java }}-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
        restore-keys: ${{ runner.os }}-JDK${{ matrix.java }}-gradle-

    - name: Build with Gradle
      run: ./gradlew clean build --no-daemon

    - name: Artifact Upload
      uses: actions/upload-artifact@v3.0.0
      with:
        name: "VeloStaffChat-JDK${{ matrix.java }}"
        path: build/libs
